security:
  user:
    password: test
    
spring:
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    datasource:
      username: sa
      password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect